/**
 * Membership admin UI strings. Temporary English literals centralized here so
 * the locale foundation (issue #58) can lift them into ICU catalogs (ADR 0010).
 */
export const membershipStrings = {
  title: "Members",
  description: "Manage organization memberships, roles, and location access.",
  invite: "Invite member",
  invitations: "Invitations",
  member: "Member",
  email: "Email",
  roles: "Roles",
  locations: "Locations",
  status: "Status",
  active: "Active",
  inactive: "Inactive",
  orgWide: "All locations",
  actions: "Actions",
  viewDetail: "View",
  deactivate: "Deactivate",
  reactivate: "Reactivate",
  inviteEmailLabel: "Email address",
  inviteRoleLabel: "Role",
  inviteSubmit: "Send invitation",
  inviteCancel: "Cancel",
  cancelInvitation: "Cancel invitation",
  roleAssignment: "Role assignment",
  assignRole: "Assign role",
  revokeRole: "Revoke",
  locationGrants: "Location access",
  grantLocation: "Grant location access",
  revokeLocation: "Revoke",
  noMembers: "No members yet.",
  backToMembers: "Back to members",
  acceptInvitation: "Accept invitation",
  decline: "Decline",
  acceptTitle: "You've been invited",
  acceptDescription: "Accept this invitation to join the organization.",
  acceptSuccess: "Invitation accepted. You can now access the organization.",
  signInToAccept: "Sign in to accept this invitation.",
  errors: {
    generic: "Something went wrong. Please try again.",
    unauthorized: "You do not have permission to manage memberships.",
    lastOwner: "The organization must retain at least one active owner.",
    escalation: "You cannot assign a role that exceeds your own permissions.",
  },
} as const;
